EducateMe4/EducateMe4/Entities/Question.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducateMe4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.ClosedAnswers = new HashSet<ClosedAnswer>();
            this.OpenAnswers = new HashSet<OpenAnswer>();
            this.Pins = new HashSet<Pin>();
            this.QuestionThemes = new HashSet<QuestionTheme>();
        }
    
        public int ID { get; set; }
        public Nullable<int> typeID { get; set; }
        public short points { get; set; }
        public string infoText { get; set; }
        public string infoYoutubeURL { get; set; }
        public string text { get; set; }
    
        public virtual ICollection<ClosedAnswer> ClosedAnswers { get; set; }
        public virtual ICollection<OpenAnswer> OpenAnswers { get; set; }
        public virtual ICollection<Pin> Pins { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual ICollection<QuestionTheme> QuestionThemes { get; set; }
    }
}

EducateMe4/EducateMe4/Entities/QuestionType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducateMe4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionType
    {
        public QuestionType()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
    }
}

EducateMe4/EducateMe4/Controllers/AnswerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EducateMe4.Entities;

namespace EducateMe4.Controllers
{
    public class AnswerController : Controller
    {
        private EducateMeEntities db = new EducateMeEntities();

        // GET: /AnswersIndex
        public ActionResult AnswersIndex(int? questionId)
        {
            if (questionId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var closedanswers = db.ClosedAnswers.Include(c => c.Question).Where(c => c.questionID == questionId.Value);
            return View(closedanswers.ToList());
        }

        // GET: /Answer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClosedAnswer closedanswer = db.ClosedAnswers.Find(id);
            if (closedanswer == null)
            {
                return HttpNotFound();
            }
            return View(closedanswer);
        }

        // GET: /Answer/Create
        public ActionResult Create()
        {
            ViewBag.questionID = new SelectList(db.Questions, "ID", "infoText");
            return View();
        }

        // POST: /Answer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,questionID,text,image,isCorrect")] ClosedAnswer closedanswer)
        {
            if (ModelState.IsValid)
            {
                db.ClosedAnswers.Add(closedanswer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.questionID = new SelectList(db.Questions, "ID", "infoText", closedanswer.questionID);
            return View(closedanswer);
        }

        // GET: /Answer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClosedAnswer closedanswer = db.ClosedAnswers.Find(id);
            if (closedanswer == null)
            {
                return HttpNotFound();
            }
            ViewBag.questionID = new SelectList(db.Questions, "ID", "infoText", closedanswer.questionID);
            return View(closedanswer);
        }

        // POST: /Answer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,questionID,text,image,isCorrect")] ClosedAnswer closedanswer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(closedanswer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.questionID = new SelectList(db.Questions, "ID", "infoText", closedanswer.questionID);
            return View(closedanswer);
        }

        // GET: /Answer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClosedAnswer closedanswer = db.ClosedAnswers.Find(id);
            if (closedanswer == null)
            {
                return HttpNotFound();
            }
            return View(closedanswer);
        }

        // POST: /Answer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ClosedAnswer closedanswer = db.ClosedAnswers.Find(id);
            db.ClosedAnswers.Remove(closedanswer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EducateMe4/EducateMe4/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EducateMe4.Entities;

namespace EducateMe4.Controllers
{
    public class QuestionController : Controller
    {
        private EducateMeEntities db = new EducateMeEntities();

        // GET: /Question/
        public ActionResult Index()
        {
            var questions = db.Questions.Include(q => q.QuestionType);
            return View(questions.ToList());
        }

        // GET: /Question/AddAnswer/5
        public ActionResult AddAnswer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClosedAnswer answer = new ClosedAnswer();
            answer.questionID = id.Value;

            db.ClosedAnswers.Add(answer);
            db.SaveChanges();

            return RedirectToAction("Answers", new {id = id});
        }

        // GET: /Question/Create
        public ActionResult Create()
        {
            ViewBag.typeID = new SelectList(db.QuestionTypes, "ID", "name");
            return View();
        }

        // POST: /Question/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,typeID,points,infoText,infoYoutubeURL,text")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.typeID = new SelectList(db.QuestionTypes, "ID", "name", question.typeID);
            return View(question);
        }

        // GET: /Question/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.typeID = new SelectList(db.QuestionTypes, "ID", "name", question.typeID);
            return View(question);
        }

        // POST: /Question/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,typeID,points,infoText,infoYoutubeURL,text")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.typeID = new SelectList(db.QuestionTypes, "ID", "name", question.typeID);
            return View(question);
        }

        // GET: /Question/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: /Question/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: /Question/Answers
        public ActionResult Answers(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }


        // GET: /Question/Answers
        public ActionResult AnswersIndex(int? questionId)
        {
            if (questionId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<ClosedAnswer> answers = db.ClosedAnswers.Where(c => c.questionID == questionId).ToList();

            return View(answers);
        }

        // POST: /Question/Delete/5
        [HttpGet, ActionName("DeleteAnswer")]
        public ActionResult Delete(int id)
        {
            ClosedAnswer answer = db.ClosedAnswers.Find(id);
            db.ClosedAnswers.Remove(answer);
            db.SaveChanges();

            return RedirectToAction("Answers", new {id = answer.questionID});
        }


        [HttpPost]
        public ActionResult SaveAnswers(List<ClosedAnswer> answers)
        {
            foreach (var answer in answers)
            {
                db.ClosedAnswers.AddOrUpdate(answer);
            }

            db.SaveChanges();

            return RedirectToAction("Answers", new { id = answers[0].questionID });
        }
    }

}

EducateMe4/EducateMe4/Views/Question/AnswerCreate.cshtml
@model EducateMe4.Entities.ClosedAnswer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ClosedAnswer</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.questionID, "questionID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("questionID", String.Empty)
                @Html.ValidationMessageFor(model => model.questionID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text)
                @Html.ValidationMessageFor(model => model.text)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image)
                @Html.ValidationMessageFor(model => model.image)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isCorrect, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.isCorrect)
                @Html.ValidationMessageFor(model => model.isCorrect)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EducateMe4/EducateMe4/Views/Question/AnswerEdit.cshtml
@model EducateMe4.Entities.ClosedAnswer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ClosedAnswer</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.questionID, "questionID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("questionID", String.Empty)
                @Html.ValidationMessageFor(model => model.questionID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text)
                @Html.ValidationMessageFor(model => model.text)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image)
                @Html.ValidationMessageFor(model => model.image)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isCorrect, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.isCorrect)
                @Html.ValidationMessageFor(model => model.isCorrect)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EducateMe4/EducateMe4/Views/Question/Answers.cshtml
@model EducateMe4.Entities.Question

@{
    ViewBag.Title = "Answers";
}

<h2>Details</h2>

<div>
    <h4>Question</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            Question
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
           Type
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuestionType.name)
        </dd>

    </dl>
</div>
<p>

    @if (Model.QuestionType.ID == 2 || Model.QuestionType.ID == 5 )
    {
        Html.RenderAction("AnswersIndex", "Question", new { questionId = Model.ID });
    }

    @*
    @if (Model.QuestionType.name == "OpenQuestion")
    {
        @Html.Partial("OpenAnswerEdit", Model);
    }
    *@

</p>

EducateMe4/EducateMe4/Views/Question/AnswersIndex.cshtml
@model List<EducateMe4.Entities.ClosedAnswer>

    <h4>Answers</h4>

    <div>
        @using (Html.BeginForm("SaveAnswers", "Question"))
        {

            <table class="table">
                <tr>
                    <th>
                        Is Correct
                    </th>
                    <th>
                        Text
                    </th>

                    <th></th>
                </tr>

                 @{ int questionId = 0; };

                @for(int i = 0; i < Model.Count; i++)
                {

                     questionId = Model[i].questionID;

                    <tr>
                        <td>
                            @Html.EditorFor(model => Model[i].isCorrect)
                        </td>
                        <td>
                            @Html.TextBoxFor(model => Model[i].text)
                        </td>

                        <td>
                            @Html.HiddenFor(model => Model[i].questionID);
                            @Html.HiddenFor(model => Model[i].ID);

                            @Html.ActionLink("Delete", "DeleteAnswer", new { id = Model[i].ID })
                        </td>

                    </tr>
                }

                    @Html.ActionLink("Add Answer", "AddAnswer", new { id = @questionId })

            </table>

            <input type="submit" value="Save Answers" class="btn btn-default" />

        }


    </div>

EducateMe4/EducateMe4/Views/Question/Index.cshtml
@model IEnumerable<EducateMe4.Entities.Question>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            #
        </th>
        <th>
            Text
        </th>
        <th>
            Type
        </th>
        <th>
            Score
        </th>
        <th>
            Info Text
        </th>

        <th>
            Info Video
        </th>
        <th></th>
    </tr>

    @{ int count = 1; }
    @foreach (var item in Model) {
        <tr>
            <td>
                @count @{ count++; }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.text)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuestionType.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.points)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.infoText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.infoYoutubeURL)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new {id = item.ID}) |
                @Html.ActionLink("Add Answer", "AddAnswer", new {id = item.ID}) |
                @Html.ActionLink("Delete", "Delete", new {id = item.ID})
            </td>
        </tr>
}

</table>